import React, { createContext, useMemo, useState } from 'react';

const dictionary = {
  en: {
    appName: 'FARM PLATFORM',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    farmerId: 'Farmer ID',
    myFarm: 'MY FARM',
    todaysMarket: "TODAY'S MARKET",
    weather: 'WEATHER',
    quickActions: 'QUICK ACTIONS',
    findCentre: 'Find Centre',
    bookSlot: 'Book Slot',
    liveQueue: 'Live Queue',
    payments: 'Payments',
    viewAll: 'VIEW ALL',
    viewDetails: 'VIEW DETAILS',
    home: 'Home',
    farm: 'Farm',
    book: 'Book',
    queue: 'Queue',
    money: 'Money',
    totalArea: 'Total Area',
    acre: 'Acre',
    acres: 'Acres',
    crops: 'Crops',
    myCrops: 'My Crops',
    addField: '+ ADD FIELD',
    cropFieldDetail: 'Crop Field Detail',
    selectedCrop: 'Selected Crop',
    area: 'Area',
    expectedYield: 'Expected Yield',
    plantingDate: 'Planting Date',
    expectedHarvest: 'Expected Harvest',
    status: 'Status',
    growing: 'Growing',
    readyForHarvest: 'Ready for Harvest',
    save: 'SAVE',
    cancel: 'Cancel',
    back: 'Back',
    next: 'Next',
    selectCrop: 'Select Crop',
    selectQuantity: 'Select Quantity',
    selectCentre: 'Select Centre',
    dateTime: 'Date & Time',
    reviewConfirm: 'Review & Confirm',
    confirmBooking: 'CONFIRM BOOKING',
    bookingConfirmed: 'Booking Confirmed',
    bookingId: 'Booking ID',
    yourToken: 'YOUR TOKEN',
    currentlyServing: 'Currently Serving',
    farmersAhead: 'Farmers Ahead',
    estimatedWait: 'Estimated Wait',
    workingNormally: 'Centre Working Normally',
    alertNear: 'Your turn is near! Token {token}, please prepare your crop.',
    turnArrived: 'YOUR TURN! Token {token}, proceed to COUNTER 2.',
    aiQualityCheck: 'AI Crop Quality Check',
    weatherAdvisory: 'Weather & Farm Advisory',
    avoidHarvestRain: 'ADVISORY: Avoid harvesting during heavy rainfall.',
    complaintsFeedback: 'Complaints & Feedback',
    raiseComplaint: 'Raise Complaint',
    rateCentre: 'Rate Centre',
    profile: 'Farmer Profile',
    logout: 'Logout',
    brandStory: '2s Brand Story',
    brandCrop: 'Your Crop,',
    brandDecision: 'Your Decision.',
    brandJourneyQuote: 'আপনার ফসলের যাত্রা, এখন আপনার হাতেই।',
    officialWeight: 'Official Weight',
    qualityGrading: 'Quality Grading',
    purchaseRecord: 'Purchase Record',
    paymentDisbursement: 'Payment Disbursement',
    confirmed: 'Confirmed',
    verified: 'Verified',
    paid: 'Paid',
    potato: 'Potato',
    rice: 'Rice',
    tomato: 'Tomato',
    onion: 'Onion',
    wheat: 'Wheat',
    maize: 'Maize'
  },
  bn: {
    appName: 'ফার্ম প্ল্যাটফর্ম',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ অপরাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    farmerId: 'কৃষক আইডি',
    myFarm: 'আমার খামার',
    todaysMarket: 'আজকের বাজার',
    weather: 'আবহাওয়া',
    quickActions: 'দ্রুত অ্যাকশন',
    findCentre: 'কেন্দ্র খুঁজুন',
    bookSlot: 'স্লট বুক করুন',
    liveQueue: 'লাইভ কিউ',
    payments: 'পেমেন্ট',
    viewAll: 'সব দেখুন',
    viewDetails: 'বিস্তারিত দেখুন',
    home: 'হোম',
    farm: 'খামার',
    book: 'বুকিং',
    queue: 'কিউ',
    money: 'অর্থ/লেনদেন',
    totalArea: 'মোট জমি',
    acre: 'একর',
    acres: 'একর',
    crops: 'ফসল',
    myCrops: 'আমার ফসলসমূহ',
    addField: '+ জমি যোগ করুন',
    cropFieldDetail: 'ফসলের জমির বিবরণ',
    selectedCrop: 'নির্বাচিত ফসল',
    area: 'জমির পরিমাণ',
    expectedYield: 'প্রত্যাশিত ফলন',
    plantingDate: 'রোপণের তারিখ',
    expectedHarvest: 'প্রত্যাশিত ফসল তোলার তারিখ',
    status: 'অবস্থা',
    growing: 'বর্ধমান',
    readyForHarvest: 'তোলার উপযুক্ত',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    back: 'পেছনে',
    next: 'পরবর্তী',
    selectCrop: 'ফসল নির্বাচন করুন',
    selectQuantity: 'পরিমাণ নির্বাচন করুন',
    selectCentre: 'সংগ্রহ কেন্দ্র বেছে নিন',
    dateTime: 'তারিখ ও সময়',
    reviewConfirm: 'পর্যালোচনা ও নিশ্চিত করুন',
    confirmBooking: 'বুকিং নিশ্চিত করুন',
    bookingConfirmed: 'বুকিং নিশ্চিত হয়েছে',
    bookingId: 'বুকিং আইডি',
    yourToken: 'আপনার টোকেন',
    currentlyServing: 'বর্তমান সেবাগ্রহণকারী',
    farmersAhead: 'সামনে অপেক্ষারত কৃষক',
    estimatedWait: 'আনুমানিক অপেক্ষা',
    workingNormally: 'কেন্দ্র স্বাভাবিকভাবে সক্রিয়',
    alertNear: 'আপনার পালা সন্নিকটে! টোকেন {token}, অনুগ্রহ করে ফসল প্রস্তুত রাখুন।',
    turnArrived: 'আপনার পালা এসেছে! টোকেন {token}, কাউন্টার ২-এ যান।',
    aiQualityCheck: 'এআই ফসল গুণমান যাচাই',
    weatherAdvisory: 'আবহাওয়া ও কৃষি পরামর্শ',
    avoidHarvestRain: 'পরামর্শ: ভারী বৃষ্টির সময় ফসল কাটা এড়িয়ে চলুন।',
    complaintsFeedback: 'অভিযোগ ও মতামত',
    raiseComplaint: 'অভিযোগ দায়ের করুন',
    rateCentre: 'কেন্দ্রের মূল্যায়ন করুন',
    profile: 'কৃষকের প্রোফাইল',
    logout: 'লগ আউট',
    brandStory: '২ সেকেন্ডের ব্র্যান্ড গল্প',
    brandCrop: 'আপনার ফসল,',
    brandDecision: 'আপনার সিদ্ধান্ত।',
    brandJourneyQuote: 'আপনার ফসলের যাত্রা, এখন আপনার হাতেই।',
    officialWeight: 'সরকারি ওজন নির্ণয়',
    qualityGrading: 'গুণমান মূল্যায়ন',
    purchaseRecord: 'ক্রয় রসিদ নথিবদ্ধ',
    paymentDisbursement: 'ব্যাংক অ্যাকাউন্টে অর্থ প্রদান',
    confirmed: 'যাচাইকৃত',
    verified: 'ভেরিফায়েড',
    paid: 'পরিশোধিত',
    potato: 'আলু',
    rice: 'ধান/চাল',
    tomato: 'টমেটো',
    onion: 'পেঁয়াজ',
    wheat: 'গম',
    maize: 'ভুট্টা'
  },
  hi: {
    appName: 'फार्म प्लेटफॉर्म',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    farmerId: 'किसान आईडी',
    myFarm: 'मेरा खेत',
    todaysMarket: 'आज का बाजार',
    weather: 'मौसम',
    quickActions: 'त्वरित क्रियाएं',
    findCentre: 'केंद्र खोजें',
    bookSlot: 'स्लॉट बुक करें',
    liveQueue: 'लाइव कतार',
    payments: 'भुगतान',
    viewAll: 'सभी देखें',
    viewDetails: 'विवरण देखें',
    home: 'होम',
    farm: 'खेत',
    book: 'बुकिंग',
    queue: 'कतार',
    money: 'पैसे',
    totalArea: 'कुल रकबा',
    acre: 'एकड़',
    acres: 'एकड़',
    crops: 'फसलें',
    myCrops: 'मेरी फसलें',
    addField: '+ नया खेत जोड़ें',
    cropFieldDetail: 'खेत व फसल का विवरण',
    selectedCrop: 'चयनित फसल',
    area: 'क्षेत्रफल',
    expectedYield: 'अपेक्षित पैदावार',
    plantingDate: 'बुवाई की तारीख',
    expectedHarvest: 'अपेक्षित कटाई तिथि',
    status: 'स्थिति',
    growing: 'बढ़ रही है',
    readyForHarvest: 'कटाई के लिए तैयार',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    back: 'पीछे',
    next: 'आगे बढ़ें',
    selectCrop: 'फसल चुनें',
    selectQuantity: 'मात्रा चुनें',
    selectCentre: 'खरीद केंद्र चुनें',
    dateTime: 'दिनांक और समय',
    reviewConfirm: 'समीक्षा और पुष्टि',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    bookingConfirmed: 'बुकिंग पक्की हो गई',
    bookingId: 'बुकिंग आईडी',
    yourToken: 'आपका टोकन',
    currentlyServing: 'वर्तमान टोकन',
    farmersAhead: 'आगे कतार में किसान',
    estimatedWait: 'अनुमानित प्रतीक्षा',
    workingNormally: 'केंद्र सुचारू रूप से कार्यरत',
    alertNear: 'आपकी बारी निकट है! टोकन {token}, कृपया अपनी फसल तैयार रखें।',
    turnArrived: 'आपकी बारी आ गई! टोकन {token}, काउंटर 2 पर जाएं।',
    aiQualityCheck: 'एआई फसल गुणवत्ता जांच',
    weatherAdvisory: 'मौसम और कृषि सलाह',
    avoidHarvestRain: 'सलाह: भारी बारिश के दौरान फसल कटाई से बचें।',
    complaintsFeedback: 'शिकायत एवं प्रतिक्रिया',
    raiseComplaint: 'शिकायत दर्ज करें',
    rateCentre: 'केंद्र को रेटिंग दें',
    profile: 'किसान प्रोफ़ाइल',
    logout: 'लॉग आउट',
    brandStory: '2-सेकंड ब्रांड यात्रा',
    brandCrop: 'आपकी फसल,',
    brandDecision: 'आपका निर्णय।',
    brandJourneyQuote: 'आपकी फसल का सफर, अब आपके ही हाथों में।',
    officialWeight: 'आधिकारिक तौल',
    qualityGrading: 'गुणवत्ता ग्रेडिंग',
    purchaseRecord: 'खरीद रसीद रिकॉर्ड',
    paymentDisbursement: 'बैंक खाते में भुगतान',
    confirmed: 'पुष्ट',
    verified: 'सत्यापित',
    paid: 'भुगतान संपन्न',
    potato: 'आलू',
    rice: 'धान/चावल',
    tomato: 'टमाटर',
    onion: 'प्याज',
    wheat: 'गेहूं',
    maize: 'मक्का'
  }
};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

  const value = useMemo(() => ({
    language,
    setLanguage: (x) => {
      localStorage.setItem('language', x);
      setLanguage(x);
    },
    t: (key, replacements = {}) => {
      let text = dictionary[language]?.[key] || dictionary.en[key] || key;
      Object.keys(replacements).forEach((placeholder) => {
        text = text.replace(`{${placeholder}}`, replacements[placeholder]);
      });
      return text;
    }
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

