import React, { createContext, useMemo, useState, useEffect } from 'react';

const dictionary = {
  en: {
    appName: 'AgriSetu',
    agriSetu: 'AgriSetu',
    goodMorning: 'Hi',
    goodAfternoon: 'Hi',
    goodEvening: 'Hi',
    farmerId: 'Farmer ID',
    myFarm: 'MY FARM',
    todaysMarket: "TODAY'S MARKET",
    weather: 'WEATHER',
    quickActions: 'QUICK ACTIONS',
    findCentre: 'Find Centre',
    bookSlot: 'Book Slot',
    liveQueue: 'Live Queue',
    payments: 'Payments',
    viewAll: 'VIEW ALL',
    viewDetails: 'VIEW DETAILS',
    home: 'Home',
    farm: 'Farm',
    book: 'Book',
    queue: 'Queue',
    money: 'Money',
    totalArea: 'Total Area',
    acre: 'Acre',
    acres: 'Acres',
    crops: 'Crops',
    myCrops: 'My Crops',
    addField: '+ ADD FIELD',
    cropFieldDetail: 'Crop Field Detail',
    selectedCrop: 'Selected Crop',
    area: 'Area',
    expectedYield: 'Expected Yield',
    plantingDate: 'Planting Date',
    expectedHarvest: 'Expected Harvest',
    status: 'Status',
    growing: 'Growing',
    readyForHarvest: 'Ready for Harvest',
    save: 'SAVE',
    cancel: 'Cancel',
    back: 'Back',
    next: 'Next',
    selectCrop: 'Select Crop',
    selectQuantity: 'Select Quantity',
    selectCentre: 'Select Centre',
    dateTime: 'Date & Time',
    reviewConfirm: 'Review & Confirm',
    confirmBooking: 'CONFIRM BOOKING',
    bookingConfirmed: 'Booking Confirmed',
    bookingId: 'Booking ID',
    yourToken: 'YOUR TOKEN',
    currentlyServing: 'Currently Serving',
    farmersAhead: 'Farmers Ahead',
    estimatedWait: 'Estimated Wait',
    workingNormally: 'Centre Working Normally',
    alertNear: 'Your turn is near! Token {token}, please prepare your crop.',
    turnArrived: 'YOUR TURN! Token {token}, proceed to COUNTER 2.',
    aiQualityCheck: 'AI Crop Quality Check',
    weatherAdvisory: 'Weather & Farm Advisory',
    avoidHarvestRain: 'ADVISORY: Avoid harvesting during heavy rainfall.',
    complaintsFeedback: 'Complaints & Feedback',
    raiseComplaint: 'Raise Complaint',
    rateCentre: 'Rate Centre',
    profile: 'Farmer Profile',
    logout: 'Logout',
    brandStory: '2s Brand Story',
    brandCrop: 'Your Crop,',
    brandDecision: 'Your Decision.',
    brandJourneyQuote: 'আপনার ফসলের যাত্রা, এখন আপনার হাতেই।',
    officialWeight: 'Official Weight',
    qualityGrading: 'Quality Grading',
    purchaseRecord: 'Purchase Record',
    paymentDisbursement: 'Payment Disbursement',
    confirmed: 'Confirmed',
    verified: 'Verified',
    paid: 'Paid',
    paddy: 'Paddy',
    rice: 'Paddy',
    wheat: 'Wheat',

    // Login screen translations
    welcomeBack: 'Welcome Back! 👋',
    loginSubtitle: 'Login to continue to AgriSetu',
    loginAs: 'LOGIN AS',
    farmerRole: 'Farmer',
    farmerDesc: 'Sell your produce',
    companyRole: 'Company',
    companyDesc: 'Buy quality produce',
    governmentRole: 'Government',
    governmentDesc: 'Admin & Policy Portal',
    agentRole: 'Agent',
    agentDesc: 'Procurement & Quality',
    proRole: 'Professional',
    proDesc: 'Inspect & verify',
    mobileNumber: 'Mobile Number',
    companyEmail: 'Company Email',
    professionalId: 'Professional ID / Email',
    enterMobile: 'Enter 10-digit mobile',
    password: 'Password',
    enterPassword: 'Enter your password',
    usePassword: 'Use Password',
    useOtp: 'Login with OTP',
    loginWithPassword: 'Login with Password',
    loginWithOtp: 'Login with OTP',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify & Login',
    enterOtp: 'Enter 6-digit OTP',
    resendOtp: 'Resend OTP',
    forgotPassword: 'Forgot Password?',
    newToAgriSetu: 'New to AgriSetu?',
    registerNow: 'Register Free',
    demoCredentials: 'Click to Auto-fill Demo Credentials:',
    resetPassword: 'RESET PASSWORD',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    updatePassword: 'Update Password',
    selectRole: 'Select Role',
    or: 'OR',
    directPlatform: 'Direct Farm-to-Company Platform',
    verifiedUsers: 'Verified Users',
    trustedSecure: 'Trusted & Secure',
    directConnection: 'Direct Connection',
    noMiddlemen: 'No Middlemen',
    farmerAccountLoaded: 'Farmer Account Loaded (Ramesh Patel)',
    governmentAccountLoaded: 'Government Admin Account Loaded (FCI / CCEA Officer)',
    professionalAccountLoaded: 'Professional Account Loaded (Inspector Suresh)',
    ready: 'Ready',
    secureLogin: 'Secure Login',
    secureLoginDesc: 'Your data is protected with encryption',
    safe100: '100% Safe',
    verifiedMarketplace: '🌾 AgriSetu Verified Marketplace',
    directApmc: 'Direct APMC & Corporate Procurement',
    madeForIndia: 'Made with ❤️ for Indian Agriculture',
    otpVerification: 'OTP VERIFICATION',
    forgotMobileDesc: 'Enter your registered mobile number to receive a verification OTP.',
    registeredMobileNumber: 'Registered Mobile Number',
    enterOtpSentTo: 'Enter the 6-digit OTP sent to',
    createNewPassword: 'CREATE NEW PASSWORD',
    passwordUpdated: 'Password Updated!',
    proceedToLogin: 'Proceed to Login',

    // Rulebook & Blueprint translations
    farmerRulebook: 'Farmer Rulebook',
    explainSimply: 'Explain Simply',
    mySale: 'MY SALE',
    mspCalculator: 'MSP Calculator',
    historicalArchive: 'Historical Archive',
    viewThisRule: 'VIEW THIS RULE',
    rulebookTitle: 'Official Procurement Rulebook & FAQ Norms',

    // Modal & Extra UI Translations
    pdfSection6: 'Profile & Settings',
    verified: 'Verified',
    linkedBank: 'Linked Bank Account',
    npciPfms: 'NPCI / PFMS Linked',
    bankName: 'Bank Name:',
    accountNumber: 'Account Number:',
    ifscCode: 'IFSC Code:',
    appLanguage: 'App Language',
    instantToggle: 'Instant toggle',
    done: 'Done',
    close: 'Close',
    fieldRegistry: 'Field Registry',
    parchaRecord: 'Parcha Land Record (Verified)',
    totalQuota: 'Total Quota',
    slotBookingWorkflow: '5-Step Slot Booking Workflow',
    stepXof5: 'Step {step} of 5',
    liveMandiQueue: 'Live Mandi Queue',
    turnArrivedNotice: 'Turn Arrived Notification:',
    alert2Ahead: 'Alert (2 Ahead):',
    procurementProgress: 'Procurement Lifecycle Progress',
    stageXof5Active: 'Stage {stage} of 5 Active',
    openWeatherFeed: 'OpenWeather Live Feed',
    fiveDayOutlook: '5-Day Procurement Weather Windows',
    humidity: 'Humidity',
    wind: 'Wind',
    rainRisk: 'Rain Risk',
    searchMandiPrice: 'Search crop mandi price (Paddy, Wheat)...',
    govtMsp: 'Govt MSP:',
    volume: 'Volume:',
    changeToday: 'today',
    gpsMatched: 'GPS: Darjeeling / Siliguri Region',
    maxDistance: 'Max distance: 50 KM',
    freeCapacity: 'Free Capacity:',
    mandiBenchmark: 'Mandi Benchmark:',
    hours: 'Hours:',
    bookSlotAt: 'Book Slot at {name}',
    dbtTransfer: 'DBT Direct Transfer',
    farmerDetails: 'Farmer Details',
    procurementPayment: 'Procurement & Payment',
    receiptNo: 'Receipt No:',
    tokenNo: 'Token No:',
    commodity: 'Commodity',
    qualityGrade: 'Quality Grade',
    weighedQty: 'Weighed Quantity',
    mspRate: 'MSP Rate',
    totalValue: 'Total Value',
    grossValuation: 'Gross Valuation:',
    netPaidAmount: 'Net Paid Amount:',
    printPdfReceipt: '🖨️ Print / Save as PDF',
    valuationSimulator: 'Rulebook Valuation Simulator',
    selectCropGrade: '1. Select Crop & Grade:',
    produceQuantity: '2. Produce Quantity (Quintals):',
    grainMoisture: '3. Grain Moisture %:',
    baseLimit: 'Base Limit:',
    estimatedGrossVal: 'Estimated Gross Value',
    moistureDeduction: 'Moisture Excess Deduction',
    netPayable: 'Net Payable Amount',
    cropJourney: 'Visual Crop Journey Transition',
    cropGrows: 'Crop grows ➔ Harvested',
    cropSells: 'Crop sells ➔ Earnings',
    earningsReach: 'Earnings reach ➔ Farmer',
    replay: 'Replay (2s)',
    enterDashboard: 'Enter Dashboard',
    paddyCommon: 'Paddy (Common)',
    paddyGradeA: 'Paddy (Grade A)'
  },
  bn: {
    appName: 'কৃষিসেতু (AgriSetu)',
    agriSetu: 'কৃষিসেতু (AgriSetu)',
    goodMorning: 'নমস্কার',
    goodAfternoon: 'নমস্কার',
    goodEvening: 'নমস্কার',
    farmerId: 'কৃষক আইডি',
    myFarm: 'আমার খামার',
    todaysMarket: 'আজকের বাজার',
    weather: 'আবহাওয়া',
    quickActions: 'দ্রুত অ্যাকশন',
    findCentre: 'কেন্দ্র খুঁজুন',
    bookSlot: 'স্লট বুক করুন',
    liveQueue: 'লাইভ কিউ',
    payments: 'পেমেন্ট',
    viewAll: 'সব দেখুন',
    viewDetails: 'বিস্তারিত দেখুন',
    home: 'হোম',
    farm: 'খামার',
    book: 'বুকিং',
    queue: 'কিউ',
    money: 'অর্থ/লেনদেন',
    totalArea: 'মোট জমি',
    acre: 'একর',
    acres: 'একর',
    crops: 'ফসল',
    myCrops: 'আমার ফসলসমূহ',
    addField: '+ জমি যোগ করুন',
    cropFieldDetail: 'ফসলের জমির বিবরণ',
    selectedCrop: 'নির্বাচিত ফসল',
    area: 'জমির পরিমাণ',
    expectedYield: 'প্রত্যাশিত ফলন',
    plantingDate: 'রোপণের তারিখ',
    expectedHarvest: 'প্রত্যাশিত ফসল তোলার তারিখ',
    status: 'অবস্থা',
    growing: 'বর্ধমান',
    readyForHarvest: 'তোলার উপযুক্ত',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    back: 'পেছনে',
    next: 'পরবর্তী',
    selectCrop: 'ফসল নির্বাচন করুন',
    selectQuantity: 'পরিমাণ নির্বাচন করুন',
    selectCentre: 'সংগ্রহ কেন্দ্র বেছে নিন',
    dateTime: 'তারিখ ও সময়',
    reviewConfirm: 'পর্যালোচনা ও নিশ্চিত করুন',
    confirmBooking: 'বুকিং নিশ্চিত করুন',
    bookingConfirmed: 'বুকিং নিশ্চিত হয়েছে',
    bookingId: 'বুকিং আইডি',
    yourToken: 'আপনার টোকেন',
    currentlyServing: 'বর্তমান সেবাগ্রহণকারী',
    farmersAhead: 'সামনে অপেক্ষারত কৃষক',
    estimatedWait: 'আনুমানিক অপেক্ষা',
    workingNormally: 'কেন্দ্র স্বাভাবিকভাবে সক্রিয়',
    alertNear: 'আপনার পালা সন্নিকটে! টোকেন {token}, অনুগ্রহ করে ফসল প্রস্তুত রাখুন।',
    turnArrived: 'আপনার পালা এসেছে! টোকেন {token}, কাউন্টার ২-এ যান।',
    aiQualityCheck: 'এআই ফসল গুণমান যাচাই',
    weatherAdvisory: 'আবহাওয়া ও কৃষি পরামর্শ',
    avoidHarvestRain: 'পরামর্শ: ভারী বৃষ্টির সময় ফসল কাটা এড়িয়ে চলুন।',
    complaintsFeedback: 'অভিযোগ ও মতামত',
    raiseComplaint: 'অভিযোগ দায়ের করুন',
    rateCentre: 'কেন্দ্রের মূল্যায়ন করুন',
    profile: 'কৃষকের প্রোফাইল',
    logout: 'লগ আউট',
    brandStory: '২ সেকেন্ডের ব্র্যান্ড গল্প',
    brandCrop: 'আপনার ফসল,',
    brandDecision: 'আপনার সিদ্ধান্ত।',
    brandJourneyQuote: 'আপনার ফসলের যাত্রা, এখন আপনার হাতেই।',
    officialWeight: 'সরকারি ওজন নির্ণয়',
    qualityGrading: 'গুণমান মূল্যায়ন',
    purchaseRecord: 'ক্রয় রসিদ নথিবদ্ধ',
    paymentDisbursement: 'ব্যাংক অ্যাকাউন্টে অর্থ প্রদান',
    confirmed: 'যাচাইকৃত',
    verified: 'ভেরিফায়েড',
    paddy: 'ধান',
    rice: 'ধান/চাল',
    wheat: 'গম',

    // Login screen translations
    welcomeBack: 'স্বাগতম! 👋',
    loginSubtitle: 'AgriSetu-এ চালিয়ে যেতে লগইন করুন',
    loginAs: 'হিসেবে লগইন করুন',
    farmerRole: 'কৃষক',
    farmerDesc: 'আপনার ফসল বিক্রি করুন',
    companyRole: 'কোম্পানি',
    companyDesc: 'গুণমানসম্মত ফসল কিনুন',
    governmentRole: 'সরকার',
    governmentDesc: 'অ্যাডমিন ও পলিসি পোর্টাল',
    agentRole: 'পেশাদার',
    agentDesc: 'সংগ্রহ ও মান নির্ধারণ',
    proRole: 'পেশাদার',
    proDesc: 'যাচাই ও পরীক্ষা করুন',
    mobileNumber: 'মোবাইল নম্বর',
    companyEmail: 'কোম্পানির ইমেল',
    professionalId: 'পেশাদার আইডি / ইমেল',
    enterMobile: '১০ সংখ্যার মোবাইল লিখুন',
    password: 'পাসওয়ার্ড',
    enterPassword: 'আপনার পাসওয়ার্ড লিখুন',
    usePassword: 'পাসওয়ার্ড ব্যবহার করুন',
    useOtp: 'ওটিপি দিয়ে লগইন করুন',
    loginWithPassword: 'পাসওয়ার্ড দিয়ে লগইন',
    loginWithOtp: 'ওটিপি দিয়ে লগইন',
    sendOtp: 'ওটিপি পাঠান',
    verifyOtp: 'যাচাই করে লগইন করুন',
    enterOtp: '৬ সংখ্যার ওটিপি লিখুন',
    resendOtp: 'পুনরায় ওটিপি পাঠান',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    newToAgriSetu: 'AgriSetu-এ নতুন?',
    registerNow: 'বিনামূল্যে নিবন্ধন করুন',
    demoCredentials: 'ডেমো তথ্য অটো-ফিল করতে ক্লিক করুন:',
    resetPassword: 'পাসওয়ার্ড রিসেট করুন',
    newPassword: 'নতুন পাসওয়ার্ড',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    updatePassword: 'পাসওয়ার্ড আপডেট করুন',
    selectRole: 'ভূমিকা নির্বাচন করুন',
    or: 'অথবা',
    directPlatform: 'খামার থেকে সরাসরি কোম্পানি প্ল্যাটফর্ম',
    verifiedUsers: 'যাচাইকৃত ব্যবহারকারী',
    trustedSecure: 'বিশ্বস্ত ও নিরাপদ',
    directConnection: 'সরাসরি সংযোগ',
    noMiddlemen: 'মধ্যস্বত্বভোগীহীন',
    farmerAccountLoaded: 'কৃষক অ্যাকাউন্ট লোড হয়েছে (রমেশ প্যাটেল)',
    governmentAccountLoaded: 'সরকারি অ্যাডমিন অ্যাকাউন্ট লোড হয়েছে (FCI / CCEA কর্মকর্তা)',
    professionalAccountLoaded: 'পেশাদার অ্যাকাউন্ট লোড হয়েছে (পরিদর্শক সুরেশ)',
    ready: 'প্রস্তুত',
    secureLogin: 'নিরাপদ লগইন',
    secureLoginDesc: 'আপনার তথ্য এনক্রিপশন দ্বারা সুরক্ষিত',
    safe100: '১০০% নিরাপদ',
    verifiedMarketplace: '🌾 কৃষিসেতু যাচাইকৃত মার্কেটপ্লেস',
    directApmc: 'সরাসরি এপিএমসি ও কর্পোরেট সংগ্রহ',
    madeForIndia: 'ভারতীয় কৃষির জন্য ❤️ ভালোবাসা সহ নির্মিত',
    otpVerification: 'ওটিপি যাচাইকরণ',
    forgotMobileDesc: 'যাচাইকরণের ওটিপি পেতে আপনার নিবন্ধিত মোবাইল নম্বর লিখুন।',
    registeredMobileNumber: 'নিবন্ধিত মোবাইল নম্বর',
    enterOtpSentTo: 'প্রেরিত ৬ সংখ্যার ওটিপি লিখুন',
    createNewPassword: 'নতুন পাসওয়ার্ড তৈরি করুন',
    passwordUpdated: 'পাসওয়ার্ড আপডেট করা হয়েছে!',
    proceedToLogin: 'লগইনে এগিয়ে যান',

    // Rulebook & Blueprint translations
    farmerRulebook: 'কৃষক রুলবুক',
    explainSimply: 'সহজ ব্যাখ্যা',
    mySale: 'আমার বিক্রি',
    mspCalculator: 'এমএসপি ক্যালকুলেটর',
    historicalArchive: 'ঐতিহাসিক আর্কাইভ',
    viewThisRule: 'এই নিয়ম দেখুন',
    rulebookTitle: 'সরকারি সংগ্রহ রুলবুক ও এফএকিউ মানদণ্ড',

    // Modal & Extra UI Translations
    pdfSection6: 'প্রোফাইল ও সেটিংস',
    verified: 'যাচাইকৃত',
    linkedBank: 'সংযুক্ত ব্যাংক অ্যাকাউন্ট',
    npciPfms: 'এনপিসিআই / পিএফএমএস সংযুক্ত',
    bankName: 'ব্যাংকের নাম:',
    accountNumber: 'অ্যাাকাউন্ট নম্বর:',
    ifscCode: 'আইএফএসসি কোড:',
    appLanguage: 'অ্যাপের ভাষা',
    instantToggle: 'তাত্ক্ষণিক পরিবর্তন',
    done: 'সম্পন্ন',
    close: 'বন্ধ করুন',
    fieldRegistry: 'জমি রেজিস্ট্রি',
    parchaRecord: 'পরচা জমির রেকর্ড (যাচাইকৃত)',
    totalQuota: 'মোট কোটা',
    slotBookingWorkflow: '৫-ধাপের স্লট বুকিং প্রক্রিয়া',
    stepXof5: 'ধাপ {step} / ৫',
    liveMandiQueue: 'লাইভ মান্ডি কিউ',
    turnArrivedNotice: 'পালার বিজ্ঞপ্তি:',
    alert2Ahead: 'সতর্কতা (২ জন বাকি):',
    procurementProgress: 'সংগ্রহ যাত্রার অগ্রগতি',
    stageXof5Active: '৫টি পর্যায়ের মধ্যে {stage} সক্রিয়',
    openWeatherFeed: 'লাইভ আবহাওয়া সংকেত',
    fiveDayOutlook: '৫ দিনের আবহাওয়ার পূর্বাভাস',
    humidity: 'আর্দ্রতা',
    wind: 'বাতাস',
    rainRisk: 'বৃষ্টির সম্ভাবনা',
    searchMandiPrice: 'শস্যের বাজার দর খুঁজুন...',
    govtMsp: 'সরকারি এমএসপি:',
    volume: 'পরিমাণ:',
    changeToday: 'আজ',
    gpsMatched: 'জিপিএস: শিলিগুড়ি অঞ্চল',
    maxDistance: 'সর্বোচ্চ দূরত্ব: ৫০ কিমি',
    freeCapacity: 'খালি ক্ষমতা:',
    mandiBenchmark: 'বাজার দর:',
    hours: 'সময়সূচী:',
    bookSlotAt: '{name}-এ স্লট বুক করুন',
    dbtTransfer: 'ডিবিটি সরাসরি হস্তান্তর',
    farmerDetails: 'কৃষকের বিবরণ',
    procurementPayment: 'সংগ্রহ ও অর্থপ্রদান',
    receiptNo: 'রসিদ নম্বর:',
    tokenNo: 'টোকেন নম্বর:',
    commodity: 'পণ্য',
    qualityGrade: 'গুণমান গ্রেড',
    weighedQty: 'পরিমাপকৃত পরিমাণ',
    mspRate: 'এমএসপি হার',
    totalValue: 'মোট মূল্য',
    grossValuation: 'মোট মূল্যায়ন:',
    netPaidAmount: 'নিট পরিশোধিত অর্থ:',
    printPdfReceipt: '🖨️ প্রিন্ট / পিডিএফ ডাউনলোড',
    valuationSimulator: 'রুলবুক মূল্যায়ন সিমুলেটর',
    selectCropGrade: '১. ফসল ও গ্রেড নির্বাচন করুন:',
    produceQuantity: '২. ফসলের পরিমাণ (কুইন্টাল):',
    grainMoisture: '৩. দানার আর্দ্রতা %:',
    baseLimit: 'মূল সীমা:',
    estimatedGrossVal: 'আনুমানিক মোট মূল্য',
    moistureDeduction: 'অতিরিক্ত আর্দ্রতার জন্য কাটছাঁট',
    netPayable: 'নিট প্রদেয় মূল্য',
    cropJourney: 'ফসলের দৃশ্যমান যাত্রার ধাপ',
    cropGrows: 'ফসল বৃদ্ধি ➔ কাটা হয়',
    cropSells: 'ফসল বিক্রি ➔ আয়',
    earningsReach: 'আয় পৌঁছায় ➔ কৃষকের কাছে',
    replay: 'পুনঃপ্রচার (২ সেকেন্ড)',
    enterDashboard: 'ড্যাশবোর্ডে প্রবেশ করুন',
    paddyCommon: 'ধান (সাধারণ)',
    paddyGradeA: 'ধান (গ্রেড এ)'
  },
  hi: {
    appName: 'कृषिसेतु (AgriSetu)',
    agriSetu: 'कृषिसेतु (AgriSetu)',
    goodMorning: 'नमस्ते',
    goodAfternoon: 'नमस्ते',
    goodEvening: 'नमस्ते',
    farmerId: 'किसान आईडी',
    myFarm: 'मेरा खेत',
    todaysMarket: 'आज का बाजार',
    weather: 'मौसम',
    quickActions: 'त्वरित क्रियाएं',
    findCentre: 'केंद्र खोजें',
    bookSlot: 'स्लॉट बुक करें',
    liveQueue: 'लाइव कतार',
    payments: 'भुगतान',
    viewAll: 'सभी देखें',
    viewDetails: 'विवरण देखें',
    home: 'होम',
    farm: 'खेत',
    book: 'बुकिंग',
    queue: 'कतार',
    money: 'पैसे',
    totalArea: 'कुल रकबा',
    acre: 'एकड़',
    acres: 'एकड़',
    crops: 'फसलें',
    myCrops: 'मेरी फसलें',
    addField: '+ नया खेत जोड़ें',
    cropFieldDetail: 'खेत व फसल का विवरण',
    selectedCrop: 'चयनित फसल',
    area: 'क्षेत्रफल',
    expectedYield: 'अपेक्षित पैदावार',
    plantingDate: 'बुवाई की तारीख',
    expectedHarvest: 'अपेक्षित कटाई तिथि',
    status: 'स्थिति',
    growing: 'बढ़ रही है',
    readyForHarvest: 'कटाई के लिए तैयार',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    back: 'पीछे',
    next: 'आगे बढ़ें',
    selectCrop: 'फसल चुनें',
    selectQuantity: 'मात्रा चुनें',
    selectCentre: 'खरीद केंद्र चुनें',
    dateTime: 'दिनांक और समय',
    reviewConfirm: 'समीक्षा और पुष्टि',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    bookingConfirmed: 'बुकिंग पक्की हो गई',
    bookingId: 'बुकिंग आईडी',
    yourToken: 'आपका टोकन',
    currentlyServing: 'वर्तमान टोकन',
    farmersAhead: 'आगे कतार में किसान',
    estimatedWait: 'अनुमानित प्रतीक्षा',
    workingNormally: 'केंद्र सुचारू रूप से कार्यरत',
    alertNear: 'आपकी बारी निकट है! टोकन {token}, कृपया अपनी फसल तैयार रखें।',
    turnArrived: 'आपकी बारी आ गई! टोकन {token}, काउंटर 2 पर जाएं।',
    aiQualityCheck: 'एआई फसल गुणवत्ता जांच',
    weatherAdvisory: 'मौसम और कृषि सलाह',
    avoidHarvestRain: 'सलाह: भारी बारिश के दौरान फसल कटाई से बचें।',
    complaintsFeedback: 'शिकायत एवं प्रतिक्रिया',
    raiseComplaint: 'शिकायत दर्ज करें',
    rateCentre: 'केंद्र को रेटिंग दें',
    profile: 'किसान प्रोफ़ाइल',
    logout: 'लॉग आउट',
    brandStory: '2-सेकंड ब्रांड यात्रा',
    brandCrop: 'आपकी फसल,',
    brandDecision: 'आपका निर्णय।',
    brandJourneyQuote: 'आपकी फसल का सफर, अब आपके ही हाथों में।',
    officialWeight: 'आधिकारिक तौल',
    qualityGrading: 'गुणवत्ता ग्रेडिंग',
    purchaseRecord: 'खरीद रसीद रिकॉर्ड',
    paymentDisbursement: 'बैंक खाते में भुगतान',
    confirmed: 'पुष्ट',
    verified: 'सत्यापित',
    paddy: 'धान',
    rice: 'धान/चावल',
    wheat: 'गेहूं',

    // Login screen translations
    welcomeBack: 'स्वागत है! 👋',
    loginSubtitle: 'AgriSetu में जारी रखने के लिए लॉगिन करें',
    loginAs: 'के रूप में लॉगिन करें',
    farmerRole: 'किसान',
    farmerDesc: 'अपनी उपज बेचें',
    companyRole: 'कंपनी',
    companyDesc: 'गुणवत्तापूर्ण उपज खरीदें',
    governmentRole: 'सरकार',
    governmentDesc: 'एडमिन व नीति पोर्टल',
    agentRole: 'एजेंट',
    agentDesc: 'खरीद व गुणवत्ता',
    proRole: 'पेशेवर',
    proDesc: 'निरीक्षण व सत्यापन करें',
    mobileNumber: 'मोबाइल नंबर',
    companyEmail: 'कंपनी ईमेल',
    professionalId: 'पेशेवर आईडी / ईमेल',
    enterMobile: '10 अंकों का मोबाइल दर्ज करें',
    password: 'पासवर्ड',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    usePassword: 'पासवर्ड का उपयोग करें',
    useOtp: 'ओटीपी से लॉगिन करें',
    loginWithPassword: 'पासवर्ड से लॉगिन',
    loginWithOtp: 'ओटीपी से लॉगिन',
    sendOtp: 'ओटीपी भेजें',
    verifyOtp: 'सत्यापित करके लॉगिन करें',
    enterOtp: '6 अंकों का ओटीपी दर्ज करें',
    resendOtp: 'पुनः ओटीपी भेजें',
    forgotPassword: 'पासवर्ड भूल गए?',
    newToAgriSetu: 'AgriSetu पर नए हैं?',
    registerNow: 'निःशुल्क पंजीकरण करें',
    demoCredentials: 'डेमो क्रेडेंशियल स्वतः भरने के लिए क्लिक करें:',
    resetPassword: 'पासवर्ड रीसेट करें',
    newPassword: 'नया पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    updatePassword: 'पासवर्ड अपडेट करें',
    selectRole: 'भूमिका चुनें',
    or: 'या',
    directPlatform: 'खेत से सीधे कंपनी प्लेटफॉर्म',
    verifiedUsers: 'सत्यापित उपयोगकर्ता',
    trustedSecure: 'विश्वसनीय एवं सुरक्षित',
    directConnection: 'सीधा संपर्क',
    noMiddlemen: 'बिना बिचौलिए',
    farmerAccountLoaded: 'किसान खाता लोड हुआ (रमेश पटेल)',
    governmentAccountLoaded: 'सरकारी एडमिन खाता लोड हुआ (FCI / CCEA अधिकारी)',
    professionalAccountLoaded: 'पेशेवर खाता लोड हुआ (निरीक्षक सुरेश)',
    ready: 'तैयार',
    secureLogin: 'सुरक्षित लॉगिन',
    secureLoginDesc: 'आपका डेटा एन्क्रिप्शन से सुरक्षित है',
    safe100: '100% सुरक्षित',
    verifiedMarketplace: '🌾 कृषिसेतु सत्यापित मार्केटप्लेस',
    directApmc: 'सीधी एपीएमसी व कॉर्पोरेट खरीद',
    madeForIndia: 'भारतीय कृषि के लिए ❤️ प्यार से निर्मित',
    otpVerification: 'ओटीपी सत्यापन',
    forgotMobileDesc: 'सत्यापन ओटीपी प्राप्त करने के लिए अपना पंजीकृत मोबाइल नंबर दर्ज करें।',
    registeredMobileNumber: 'पंजीकृत मोबाइल नंबर',
    enterOtpSentTo: 'को भेजा गया 6 अंकों का ओटीपी दर्ज करें',
    createNewPassword: 'नया पासवर्ड बनाएं',
    passwordUpdated: 'पासवर्ड अपडेट हो गया!',
    proceedToLogin: 'लॉगिन के लिए आगे बढ़ें',

    // Rulebook & Blueprint translations
    farmerRulebook: 'किसान नियम पुस्तिका',
    explainSimply: 'सरल व्याख्या',
    mySale: 'मेरी बिक्री',
    mspCalculator: 'एमएसपी कैलकुलेटर',
    historicalArchive: 'ऐतिहासिक संग्रह',
    viewThisRule: 'यह नियम देखें',
    rulebookTitle: 'सरकारी खरीद नियम पुस्तिका व मानक',

    // Modal & Extra UI Translations
    pdfSection6: 'प्रोफ़ाइल एवं सेटिंग्स',
    verified: 'सत्यापित',
    linkedBank: 'लिंक किया गया बैंक खाता',
    npciPfms: 'एनपीसीआई / पीएफएमएस लिंक',
    bankName: 'बैंक का नाम:',
    accountNumber: 'खाता संख्या:',
    ifscCode: 'आईएफएससी कोड:',
    appLanguage: 'ऐप भाषा',
    instantToggle: 'तुरंत बदलें',
    done: 'संपन्न',
    close: 'बंद करें',
    fieldRegistry: 'खेत रजिस्ट्री',
    parchaRecord: 'पर्चा भूमि रिकॉर्ड (सत्यापित)',
    totalQuota: 'कुल कोटा',
    slotBookingWorkflow: '5-चरण स्लॉट बुकिंग प्रक्रिया',
    stepXof5: 'चरण {step} / 5',
    liveMandiQueue: 'लाइव मंडी कतार',
    turnArrivedNotice: 'बारी आने की सूचना:',
    alert2Ahead: 'अलर्ट (2 आगे):',
    procurementProgress: 'खरीद जीवनचक्र की प्रगति',
    stageXof5Active: '5 में से चरण {stage} सक्रिय',
    openWeatherFeed: 'लाइव मौसम अपडेट',
    fiveDayOutlook: '5-दिवसीय मौसम पूर्वावलोकन',
    humidity: 'आर्द्रता',
    wind: 'हवा',
    rainRisk: 'बारिश का जोखिम',
    searchMandiPrice: 'फसल मंडी भाव खोजें...',
    govtMsp: 'सरकारी एमएसपी:',
    volume: 'मात्रा:',
    changeToday: 'आज',
    gpsMatched: 'जीपीएस: सिलीगुड़ी क्षेत्र',
    maxDistance: 'अधिकतम दूरी: 50 किमी',
    freeCapacity: 'खाली क्षमता:',
    mandiBenchmark: 'मंडी मानक:',
    hours: 'कार्य समय:',
    bookSlotAt: '{name} पर स्लॉट बुक करें',
    dbtTransfer: 'डीबीटी सीधा हस्तांतरण',
    farmerDetails: 'किसान का विवरण',
    procurementPayment: 'खरीद एवं भुगतान',
    receiptNo: 'रसीद नंबर:',
    tokenNo: 'टोकन नंबर:',
    commodity: 'जिंस',
    qualityGrade: 'गुणवत्ता ग्रेड',
    weighedQty: 'तौला गया वजन',
    mspRate: 'एमएसपी दर',
    totalValue: 'कुल मूल्य',
    grossValuation: 'सकल मूल्यांकन:',
    netPaidAmount: 'शुद्ध भुगतान राशि:',
    printPdfReceipt: '🖨️ प्रिंट / पीडीएफ डाउनलोड',
    valuationSimulator: 'नियम पुस्तिका मूल्यांकन सिमुलेटर',
    selectCropGrade: '1. फसल और ग्रेड चुनें:',
    produceQuantity: '2. उपज की मात्रा (कुंतल):',
    grainMoisture: '3. अनाज की नमी %:',
    baseLimit: 'मूल सीमा:',
    estimatedGrossVal: 'अनुमानित सकल मूल्य',
    moistureDeduction: 'नमी कटौती',
    netPayable: 'शुद्ध देय राशि',
    cropJourney: 'दृश्य फसल यात्रा का चरण',
    cropGrows: 'फसल वृद्धि ➔ कटाई',
    cropSells: 'फसल बिक्री ➔ आय',
    earningsReach: 'आय ➔ किसान तक',
    replay: 'रीप्ले (2 से)',
    enterDashboard: 'डैशबोर्ड में प्रवेश करें',
    paddyCommon: 'धान (सामान्य)',
    paddyGradeA: 'धान (ग्रेड ए)'
  }
};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

  useEffect(() => {
    document.documentElement.setAttribute('data-lang', language);
    document.body.className = `lang-${language}`;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage: (x) => {
      localStorage.setItem('language', x);
      setLanguage(x);
      document.documentElement.setAttribute('data-lang', x);
      document.body.className = `lang-${x}`;
    },
    t: (key, replacements = {}) => {
      let text = dictionary[language]?.[key] || dictionary.en[key] || key;
      Object.keys(replacements).forEach((placeholder) => {
        text = text.replace(`{${placeholder}}`, replacements[placeholder]);
      });
      return text;
    }
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

